version: '3.1'

services:
  db:
    container_name: db_jordi_alerts_channel
    image: 'mariadb:10.7.3-focal'
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=r00t
      - TZ=Europe/Madrid
      - MYSQL_DATABASE=db_name
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass
    restart: always
